---
name: Bot-BasicBot-Pluggable-Module-Eliza
version: 0.03
author: []
abstract: Eliza for Bot::BasicBot::Pluggable
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Bot::BasicBot::Pluggable: 0.5
  Chatbot::Eliza: 0
build_requires:
  Test::More: 0
provides:
  Bot::BasicBot::Pluggable::Module::Eliza:
    file: lib/Bot/BasicBot/Pluggable/Module/Eliza.pm
    version: 0.03
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
